
[database]
host = "127.0.0.1"
port = 27017
name = "rdi5skypro"

[server]
port = 65231

[mcsm]
host = "127.0.0.1"
port = 23333
apiKey = "c1354eff4a604de39e67b550df6ed607"
daemonId = "87f1a66a45ec4326a7ad85bebebc77ea"

[docker]
host = "127.0.0.1"
port = 2376
tlsEnabled = false
tlsVerify = false
certPath = ""
keyPath = ""
caPath = ""
apiVersion = "1.41"